services:
  # portainer:
  #   image: portainer/portainer-ce:${PORTAINER_VERSION}
  #   container_name: portainer
  #   restart: always
  #   command: --admin-password-file=/run/secrets/portainer-admin-password
  #   ports: 
  #     - "8084:9000"
  #   secrets:
  #     - portainer-admin-password
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

  # akhq:
  #   image: tchiotludo/akhq:${AKHQ_VERSION}
  #   container_name: akhq
  #   restart: always
  #   ports:
  #     - 8086:8080
  #   environment:
  #     AKHQ_CONFIGURATION: |
  #       akhq:
  #         connections:
  #           docker-kafka-server:
  #             properties:
  #               bootstrap.servers: "kafka:9092"
  #   depends_on:
  #     - kafka
  #   networks:
  #     - kafka

  aas-gui:
    image: eclipsebasyx/aas-gui:${AAS_WEBUI_VERSION}
    container_name: aas-gui
    restart: always
    ports:
      - 8099:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
      AAS_DISCOVERY_PATH: http://localhost:9100
      AAS_REGISTRY_PATH: http://localhost:8083
      SUBMODEL_REGISTRY_PATH: http://localhost:8082
      AAS_REPO_PATH: http://localhost:8081/shells
      SUBMODEL_REPO_PATH: http://localhost:8081/submodels
      CD_REPO_PATH: http://localhost:8081/concept-descriptions
    depends_on:
      aas-registry:
        condition: service_healthy
      submodel-registry:
        condition: service_healthy    
      aas-environment:
        condition: service_healthy

  # kafka-connect-ui:
  #   container_name: kafka-connect-ui
  #   image: landoop/kafka-connect-ui:0.9.7
  #   restart: always
  #   ports:
  #     - "8094:8000"
  #   environment:
  #     CONNECT_URL: "http://kafka-connect:8083" 
  #   networks:
  #     - kafka-connect
  #   depends_on:
  #     kafka-connect:
  #       condition: service_healthy

  

secrets:
  portainer-admin-password:
    environment: PORTAINER_ADMIN_PASSWORD
