package de.dfki.cos.aas2graph.kafka.model.operations;

public enum OperationType {
	POST_SHELL, POST_SUBMODEL, PUT_ASSET_INFORMATION, POST_SUBMODEL_ELEMENT, POST_SUBMODEL_REF, DELETE_SUBMODEL_REF, DELETE_SHELL,
	DELETE_SUBMODEL, PUT_SHELL, PUT_SUBMODEL, DELETE_SUBMODEL_ELEMENT
}

